apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOncePod   
  resources:
    requests:
      storage: 1Gi
  storageClassName: "rook-ceph-block"  
