---
crio_packages:
  - cri-o
  - cri-tools

# Fedora doesn't have cri-o 1.21 packages
crio_kubernetes_version_matrix:
  "1.21": "1.20"
  "1.20": "1.20"
  "1.19": "1.19"
crio_version: "{{ crio_kubernetes_version_matrix[crio_required_version] | default('1.20') }}"
