apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-notification-endpoint
spec:
  selector:
    matchLabels:
      run: my-notification-endpoint
  replicas: 2
  template:
    metadata:
      labels:
        run: my-notification-endpoint
    spec:
      containers:
        - name: my-notification-endpoint
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-notification-endpoint
  labels:
    run: my-notification-endpoint
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    run: my-notification-endpoint
