---
crio_versioned_pkg:
  "1.22":
    - "cri-o-1.22.*"
  "1.21":
    - "cri-o-1.21.*"
  "1.20":
    - "cri-o-1.20.*"

default_crio_packages: "{{ crio_versioned_pkg[crio_version] }}"

crio_packages: "{{ centos_crio_packages | default(default_crio_packages) }}"
