---
crio_packages:
  - cri-o
  - cri-tools

crio_kubernetes_version_matrix:
  "1.22": "1.22"
  "1.21": "1.21"
  "1.20": "1.20"
crio_version: "{{ crio_kubernetes_version_matrix[crio_required_version] | default('1.20') }}"
