---
- name: install | Download etcd and etcdctl
  include_tasks: "../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.etcd) }}"
  when: etcd_cluster_setup
  tags:
    - never
    - etcd

- name: install | Copy etcd and etcdctl binary from download dir
  copy:
    src: "{{ local_release_dir }}/etcd-{{ etcd_version }}-linux-{{ host_architecture }}/{{ item }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: 0755
    remote_src: yes
  with_items:
    - etcd
    - etcdctl
  when: etcd_cluster_setup
