apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
spec:
  containers:
  - name: memory-demo-2
    image: polinux/stress
    resources:
      requests:
        memory: "3Gi"
      limits:
        memory: "6Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "5500M", "--vm-hang", "1"]
  nodeSelector:
    kubernetes.io/hostname: ubun20-01
