kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wordpress-namespace-full-access
  namespace: wordpress
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]