kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: erp-namespace-full-access
  namespace: erp
subjects:
- kind: ServiceAccount
  name: erp-user
  namespace: erp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: erp-namespace-full-access