---
# https://docs.docker.com/install/linux/docker-ce/fedora/
# https://download.docker.com/linux/fedora/<fedora-version>/x86_64/stable/Packages/
docker_versioned_pkg:
  'latest': docker-ce
  '19.03': docker-ce-19.03.15-3.fc{{ ansible_distribution_major_version }}
  '20.10': docker-ce-20.10.7-3.fc{{ ansible_distribution_major_version }}
  'stable': docker-ce-20.10.7-3.fc{{ ansible_distribution_major_version }}
  'edge': docker-ce-20.10.7-3.fc{{ ansible_distribution_major_version }}

docker_cli_versioned_pkg:
  'latest': docker-ce-cli
  '19.03': docker-ce-cli-19.03.15-3.fc{{ ansible_distribution_major_version }}
  '20.10': docker-ce-cli-20.10.7-3.fc{{ ansible_distribution_major_version }}

docker_package_info:
  enablerepo: "docker-ce"
  pkgs:
    - "{{ containerd_versioned_pkg[containerd_version | string] }}"
    - "{{ docker_cli_versioned_pkg[docker_cli_version | string] }}"
    - "{{ docker_versioned_pkg[docker_version | string] }}"
