---
- name: wait for cilium
  when:
    - needs_cordoning|default(false)
    - kube_network_plugin == 'cilium'
  command: >
    {{ bin_dir }}/kubectl --kubeconfig {{ kube_config_dir }}/admin.conf
    wait pod -n kube-system -l k8s-app=cilium
    --field-selector 'spec.nodeName=={{ kube_override_hostname|default(inventory_hostname) }}'
    --for=condition=Ready
    --timeout={{ upgrade_post_cilium_wait_timeout }}
  delegate_to: "{{ groups['kube_control_plane'][0] }}"

- name: Uncordon node
  command: "{{ bin_dir }}/kubectl --kubeconfig {{ kube_config_dir }}/admin.conf uncordon {{ kube_override_hostname|default(inventory_hostname) }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when:
    - needs_cordoning|default(false)
