---
- name: Converge
  hosts: all
  become: true
  vars:
    kata_containers_enabled: true
  roles:
    - role: kubespray-defaults
    - role: container-engine/containerd
    - role: container-engine/kata-containers
