apiVersion: v2
appVersion: 2.5.0
dependencies:
- alias: minio
  condition: minio.enabled
  name: minio
  repository: https://helm.min.io/
  version: 8.0.9
description: Helm chart for Grafana Loki in simple, scalable mode
home: https://grafana.github.io/helm-charts
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
maintainers:
- name: trevorwhitney
name: loki-simple-scalable
sources:
- https://github.com/grafana/loki
- https://grafana.com/oss/loki/
- https://grafana.com/docs/loki/latest/
type: application
version: 1.2.0
