---
- name: ovn4nfv | Label control-plane node
  command: >-
    {{ bin_dir }}/kubectl label --overwrite node {{ groups['kube_control_plane'] | first }} ovn4nfv-k8s-plugin=ovn-control-plane
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: ovn4nfv | Create ovn4nfv-k8s manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/{{ item.file }}"
  with_items:
    - {name: ovn-daemonset, file: ovn-daemonset.yml}
    - {name: ovn4nfv-k8s-plugin, file: ovn4nfv-k8s-plugin.yml}
  register: ovn4nfv_node_manifests
