---
containerd_version: 1.4.3

containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.3.7': "{{ containerd_package }}=1.3.7-1"
  '1.3.9': "{{ containerd_package }}=1.3.9-1"
  '1.4.3': "{{ containerd_package }}=1.4.3-1"
  'stable': "{{ containerd_package }}=1.4.3-1"
  'edge': "{{ containerd_package }}=1.4.3-1"
