apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
  - name: "vote-service"
    # port: 5000
    port: 80
    targetPort: 80
    # nodePort: 31000
  selector:
    app: vote
  
