apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-namespace
  namespace: argocd  # 반드시 argocd namespace여야 한다
spec:
  destination:
    namespace: rabbitmq
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.spk.io/spk/mytest.git
    path: 06.rabbitmq/rabbitmq-8-24.2
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true