all:
  hosts:
    ubun20-01:
      ansible_host: ubun20-01                                                     
    ubun20-02:
      ansible_host: ubun20-02
    ubun20-03:
      ansible_host: ubun20-03
    ubun20-04:
      ansible_host: ubun20-04
  children:
    kube_control_plane:                                                                         
      hosts:
        ubun20-01:
        ubun20-02:
        ubun20-03:
    kube-node:                                                                                              
      hosts:
        ubun20-01:
        ubun20-02:
        ubun20-03:
        ubun20-04:
    etcd:                                                                                         
      hosts:
        ubun20-01:
        ubun20-02:
        ubun20-03:
    k8s-cluster:
      children:
        kube_control_plane:
        kube-node:
    calico-rr:  
      hosts: {}