---

crio_storage_driver: "overlay"

crio_versioned_pkg:
  "1.21":
    - "cri-o-1.21.*"
  "1.20":
    - "cri-o-1.20.*"
  "1.19":
    - "cri-o-1.19.*"

default_crio_packages: "{{ crio_versioned_pkg[crio_version] }}"

crio_packages: "{{ centos_crio_packages | default(default_crio_packages) }}"
