---
docker_version: '20.10'
docker_cli_version: "{{ docker_version }}"

docker_package_info:
  pkgs:

docker_repo_key_info:
  repo_keys:

docker_repo_info:
  repos:

docker_cgroup_driver: systemd

yum_repo_dir: /etc/yum.repos.d

docker_bin_dir: "/usr/bin"

# flag to enable/disable docker cleanup
docker_orphan_clean_up: false

# old docker package names to be removed
docker_remove_packages_yum:
  - docker
  - docker-common
  - docker-engine
  - docker-selinux.noarch
  - docker-client
  - docker-client-latest
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine-selinux.noarch

docker_remove_packages_apt:
  - docker
  - docker-engine
  - docker.io
