---
- name: Helm | Download helm
  include_tasks: "../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.helm) }}"

- name: Helm | Copy helm binary from download dir
  synchronize:
    src: "{{ local_release_dir }}/helm-{{ helm_version }}/linux-{{ image_arch }}/helm"
    dest: "{{ bin_dir }}/helm"
    compress: no
    perms: yes
    owner: no
    group: no
  delegate_to: "{{ inventory_hostname }}"

- name: Helm | Check if bash_completion.d folder exists  # noqa 503
  stat:
    path: "/etc/bash_completion.d/"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: stat_result

- name: Helm | Get helm completion
  command: "{{ bin_dir }}/helm completion bash"
  changed_when: False
  register: helm_completion
  check_mode: False
  when: stat_result.stat.exists

- name: Helm | Install helm completion
  copy:
    dest: /etc/bash_completion.d/helm.sh
    content: "{{ helm_completion.stdout }}"
  become: True
  when: stat_result.stat.exists
