---
- name: Krew | Download krew
  include_tasks: "../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.krew) }}"

- name: Krew | krew env
  template:
    src: krew.j2
    dest: /etc/bash_completion.d/krew

- name: Krew | Copy krew manifest
  template:
    src: krew.yml.j2
    dest: "{{ local_release_dir }}/krew.yml"

- name: Krew | Install krew  # noqa 301 305
  shell: "{{ local_release_dir }}/krew-linux_{{ image_arch }} install --archive={{ local_release_dir }}/krew.tar.gz --manifest={{ local_release_dir }}/krew.yml"
  environment:
    KREW_ROOT: "{{ krew_root_dir }}"
    KREW_DEFAULT_INDEX_URI: "{{ krew_default_index_uri | default('') }}"
