---
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint -c ../../../.yamllint .
platforms:
  - name: ubuntu1804
    box: generic/ubuntu1804
    cpus: 2
    memory: 1024
    groups:
      - kube_control_plane
  - name: centos7
    box: centos/7
    cpus: 2
    memory: 1024
    groups:
      - kube_control_plane
  - name: centos8
    box: centos/8
    cpus: 2
    memory: 1024
    groups:
      - kube_control_plane
  - name: fedora
    box: fedora/33-cloud-base
    cpus: 2
    memory: 1024
    groups:
      - kube_control_plane
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ../../../.ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
