---
- name: nerdctl | Download nerdctl
  include_tasks: "../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.nerdctl) }}"

- name: nerdctl | Copy nerdctl binary from download dir
  copy:
    src: "{{ local_release_dir }}/nerdctl"
    dest: "{{ bin_dir }}/nerdctl"
    mode: 0755
    remote_src: true
  notify:
    - Get nerdctl completion
    - Install nerdctl completion
