---
containerd_package_info:
  pkgs:
    - "{{ containerd_versioned_pkg[containerd_version | string] }}"

containerd_repo_key_info:
  url: '{{ containerd_ubuntu_repo_gpgkey }}'
  repo_keys:
    - '{{ containerd_ubuntu_repo_repokey }}'

containerd_repo_info:
  repos:
    - >
      deb {{ containerd_ubuntu_repo_base_url }}
      {{ ansible_distribution_release|lower }}
      {{ containerd_ubuntu_repo_component }}
