#################################################################################################################
# Create an object store with settings for replication in a production environment. A minimum of 3 hosts with
# OSDs are required in this example.
#  kubectl create -f object.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: external-store
  namespace: rook-ceph # namespace:cluster
spec:
  gateway:
    # The port on which **ALL** the gateway(s) are listening on.
    # Passing a single IP from a load-balancer is also valid.
    port: 80
    externalRgwEndpoints:
      - ip: 192.168.39.182
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
